language:
  - objective-c

env:
  - NODE_VERSION="2.5.0"

install:
  - brew update
  - brew install nvm
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install
  - npm test

after_success:
  - npm run distribute