# Test against this version of Node.js
environment:
  nodejs_version: "4.1.1"
  PUBLISH_TOKEN:
    secure: w/pAoJMD7xgxclssGbzQOfgs81EQyiAfkRJMeH6e6bPiJXyUHtr403v9z10zb4GZ
  WIN_CERTIFICATE_PASSWORD:
    secure: XiZURshRBagjOmfggTF+jxSgikSYaNFr79q/zSPKkQo=

platform:
  - x86

branches:
  only:
    - autoupdate

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt tools\windows\livestyle.pfx.enc -secret %WIN_CERTIFICATE_PASSWORD% -out tools\windows\livestyle.pfx
  - npm install

test_script:
  - npm run publish

artifacts:
  - path: livestyle-win32.zip

# Don't actually build.
build: off